name: User Windows Build

on:
  workflow_dispatch:

env:
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  RUST_VERSION: "1.75"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.6"
  RUSTDESK_DEFAULT_RENDEZVOUS_SERVER: "rustdesk.kinzersky.ru"
  RUSTDESK_DEFAULT_RELAY_SERVER: "rustdesk.kinzersky.ru"
  RUSTDESK_DEFAULT_API_SERVER: "https://rustdesk.kinzersky.ru:21114"
  RUSTDESK_DEFAULT_KEY: "eL7p3CELv+zv++GpBeK6rGwzIoiOw3ykBUD2CtarQwo="

jobs:
  build-windows:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Replace engine with rustdesk custom flutter engine
        shell: pwsh
        run: |
          flutter doctor -v
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          Move-Item -Force windows-x64-release/* "C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/"

      - name: Patch flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff "$(dirname "$(dirname "$(which flutter)")")"
          cd "$(dirname "$(dirname "$(which flutter)")")"
          git apply flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: windows-2022

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        shell: bash
        run: |
          "$VCPKG_ROOT"/vcpkg install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"

      - name: Build RustDesk
        shell: pwsh
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          Move-Item .\flutter\build\windows\x64\runner\Release .\rustdesk

      - name: Add usbmmidd
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip -OutFile usbmmidd_v2.zip
          Expand-Archive usbmmidd_v2.zip -DestinationPath .
          Remove-Item -Path usbmmidd_v2\Win32 -Recurse
          Remove-Item -Path "usbmmidd_v2\deviceinstaller64.exe", "usbmmidd_v2\deviceinstaller.exe", "usbmmidd_v2\usbmmidd.bat"
          Move-Item -Force .\usbmmidd_v2 .\rustdesk

      - name: Add printer driver
        shell: pwsh
        run: |
          try {
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/rustdesk_printer_driver_v4-1.4.zip -OutFile rustdesk_printer_driver_v4-1.4.zip
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/printer_driver_adapter.zip -OutFile printer_driver_adapter.zip
            Expand-Archive rustdesk_printer_driver_v4-1.4.zip -DestinationPath .
            New-Item -ItemType Directory -Force -Path .\rustdesk\drivers | Out-Null
            Move-Item -Force .\rustdesk_printer_driver_v4-1.4 .\rustdesk\drivers\RustDeskPrinterDriver
            Expand-Archive printer_driver_adapter.zip -DestinationPath .
            Move-Item -Force .\printer_driver_adapter.dll .\rustdesk
          } catch {
            Write-Host "Ignore printer driver error."
          }

      - name: Find Runner.res
        continue-on-error: true
        shell: bash
        run: |
          runner_res=$(find . -name "Runner.res" | head -n 1)
          if [ -n "$runner_res" ]; then
            cp "$runner_res" ./libs/portable/Runner.res
          fi

      - name: Build portable packer
        shell: bash
        run: |
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../rustdesk/ -o . -e ../../rustdesk/rustdesk.exe
          popd
          mkdir -p ./artifacts
          mv ./target/release/rustdesk-portable-packer.exe ./artifacts/rustdesk-1.4.6-x86_64-portable.exe

      - name: Pack folder build
        shell: bash
        run: |
          mkdir -p ./artifacts
          cd ./rustdesk
          powershell -Command "Compress-Archive -Path * -DestinationPath ../artifacts/rustdesk-1.4.6-x86_64-editable.zip -Force"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-user-windows-x86_64
          path: artifacts
